apiVersion: apps/v1
kind: Deployment
metadata:
  name: cndp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cndp-api
  template:
    metadata:
      labels:
        app: cndp-api
    spec:
      containers:
      - name: cndp-api
        image: cndpacr12345.azurecr.io/cndp-api:2b3eb17ff9d6890da072a7100cd829b6d20da378
        ports:
        - containerPort: 5000