apiVersion: apps/v1
kind: Deployment
metadata:
  name: cndp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cndp-api
  template:
    metadata:
      labels:
        app: cndp-api
    spec:
      containers:
      - name: cndp-api
        image: cndpacr12345.azurecr.io/cndp-api:0940e15893b4694097bb03aa2fc66712e3509b5f
        ports:
        - containerPort: 5000