apiVersion: apps/v1
kind: Deployment
metadata:
  name: cndp-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cndp-api
  template:
    metadata:
      labels:
        app: cndp-api
    spec:
      containers:
      - name: cndp-api
        image: cndpacr12345.azurecr.io/cndp-api:51a4ee6ed66941552e60a85d00e15352439960df
        ports:
        - containerPort: 5000