appName: cndp-api

replicaCount: 1

image:
  repository: cndpacr12345.azurecr.io/cndp-api
  tag: latest

service:
  port: 80
  targetPort: 5000

serviceAccount:
  create: true
  name: cndp-api

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: example.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2

httpRoute:
  enabled: false