apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels: 
    app: {{.Values.appName}}
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}

          resources:
            requests:
              memory: {{ .Values.resources.request.memory}}
              cpu: {{ .Values.resources.request.cpu}}
            limits:
              memory: {{ .Values.resources.limits.memory}}
              cpu: {{ .Values.resources.limits.cpu}}

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10  